# Generated by Django 5.2.17 on 2026-10-04 04:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='challenges/')),
                ('image_url', models.URLField(blank=True)),
                ('alt_text', models.CharField(max_length=180)),
                ('caption', models.CharField(max_length=90)),
                ('photo_note', models.CharField(max_length=180)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=80)),
                ('event_at', models.DateTimeField()),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('place', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_at'],
            },
        ),
    ]
