create or replace function public.is_media_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'media_admin') = 'true', false);
$$;

create table public.challenges (
  id bigint generated by default as identity primary key,
  image_url text not null default '',
  image_path text,
  alt_text varchar(180) not null,
  caption varchar(90) not null,
  photo_note varchar(180) not null,
  title varchar(100) not null,
  category varchar(80) not null,
  event_at timestamptz not null,
  latitude double precision not null,
  longitude double precision not null,
  place varchar(120) not null,
  description varchar(1200) not null,
  is_active boolean not null default true,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint challenges_photo_required check (
    (image_path is not null and image_path <> '') or btrim(image_url) <> ''
  ),
  constraint challenges_text_required check (
    btrim(alt_text) <> '' and btrim(caption) <> '' and btrim(photo_note) <> ''
    and btrim(title) <> '' and btrim(category) <> '' and btrim(place) <> ''
    and btrim(description) <> ''
  ),
  constraint challenges_event_window check (
    event_at >= timestamptz '2026-09-01 00:00:00-05'
    and event_at <= timestamptz '2027-06-01 23:59:00-05'
  ),
  constraint challenges_us_coordinates check (
    (latitude between 24 and 50 and longitude between -126 and -66)
    or (latitude between 51 and 73 and longitude between -180 and -129)
    or (latitude between 18 and 23 and longitude between -161 and -154)
  )
);

create index challenges_active_event_at_idx on public.challenges (event_at desc) where is_active;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger challenges_set_updated_at
before update on public.challenges
for each row execute function public.set_updated_at();

alter table public.challenges enable row level security;
revoke all on public.challenges from public, anon, authenticated;
grant select (
  id, image_url, image_path, alt_text, caption, photo_note, title, category,
  event_at, latitude, longitude, place, description, is_active
) on public.challenges to anon, authenticated;
grant insert (
  image_url, image_path, alt_text, caption, photo_note, title, category,
  event_at, latitude, longitude, place, description, is_active, created_by
) on public.challenges to authenticated;
grant update (
  image_url, image_path, alt_text, caption, photo_note, title, category,
  event_at, latitude, longitude, place, description, is_active
) on public.challenges to authenticated;
grant delete on public.challenges to authenticated;
revoke all on sequence public.challenges_id_seq from public, anon, authenticated;
grant usage, select on sequence public.challenges_id_seq to authenticated;

create policy "Anyone can read active challenges"
on public.challenges for select
to anon, authenticated
using (is_active or public.is_media_admin());

create policy "Media admins can insert challenges"
on public.challenges for insert
to authenticated
with check (public.is_media_admin() and created_by = auth.uid());

create policy "Media admins can update challenges"
on public.challenges for update
to authenticated
using (public.is_media_admin())
with check (public.is_media_admin());

create policy "Media admins can delete challenges"
on public.challenges for delete
to authenticated
using (public.is_media_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'challenge-photos',
  'challenge-photos',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Media admins can upload challenge photos"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'challenge-photos'
  and public.is_media_admin()
);

create policy "Media admins can list challenge photos"
on storage.objects for select
to authenticated
using (
  bucket_id = 'challenge-photos'
  and public.is_media_admin()
);

create policy "Media admins can replace challenge photos"
on storage.objects for update
to authenticated
using (
  bucket_id = 'challenge-photos'
  and public.is_media_admin()
)
with check (
  bucket_id = 'challenge-photos'
  and public.is_media_admin()
);

create policy "Media admins can remove challenge photos"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'challenge-photos'
  and public.is_media_admin()
);
